# Одномерные массивы (векторы)


In [ ]:
from numpy import *

a = np.array([1,2,4])
print(a, type(a))

[1 2 4] <class 'numpy.ndarray'>


In [ ]:
b = np.array([0., 2,1])
print(b.dtype)
print(b.astype(int))

float64
[0 2 1]


In [ ]:
print(type(np.arange(0,8)))

<class 'numpy.ndarray'>


In [ ]:
a = np.arange(10, -1, -1)
a = np.delete(a, [5, 7])
print(a)

[10  9  8  7  6  4  2  1  0]
